### PR TITLE
Upgrade to django 1.7 migrations

### PR DESCRIPTION
**Pull request by josjevv**

### CODE REVIEW

**Comment by StriveForBest** [comment]
@digi604, @josjevv guys, what's up with this PR? is it good to go into master? it's still hasn't been resolved in master branch.

**Comment by josjevv** [comment]
I am just a contributor, not a maintainer. I was not able to reach @digi604 about this change. Since I needed this change for one of my projects, I created a fork and published this on pypi. You can just run `pip install djangocms-table-changer` until the day this will be accepted ;)

**Comment by StriveForBest** [comment]
@josjevv gotcha, i ended up forking it and fixing it in my fork too... thanks!

**Comment by stefanfoulis** [comment]
@josjevv sorry for the long wait. this was totally forgotten.

**Pull request merged**
